### ISSUE TITLE
Buttons all jammed together 

### ISSUE THREAD

**Issue by Sepero** [billthefarmer/accordion#1]
I downloaded this app from f-droid just for fun. When I load it, the keys are are jammed together. Several of the instrument keys overlap each other. I have a Samsung Galaxy S5 1080p phone.

**Comment by hackerb9** [comment]
Bill, it'd be very nice if you'd consider an option to make the buttons scale down for smaller screens. You could include a warning that it might not be playable. I think it would still be useful for people learning to play (or thinking about learning to play) the accordion.
