### ISSUE TITLE
A confusing icon on accordion 's UI

### ISSUE THREAD

**Issue by b450mhdv** [billthefarmer/accordion#14]
@billthefarmer

Hello, I found a problem with the app's UI design. When I first used this app, I was curious about the "Reverse" icon in the settings page. I thought this widget was used to do some random tasks, but it was used to reverse the buttons. Although this icon seems to have something to do with "Reverse", this icon is different from the common icon I saw in other popular apps. In short, I think this widget may confuse users. For better user experience, could you fix this issue?
![accordion-github](https://user-images.githubusercontent.com/78015408/112107245-a792f900-8be9-11eb-99dc-1b7079d74676.png)

**Comment by billthefarmer** [comment]
The reason for reversing the buttons is for left handed people who prefer to play with the instrument buttons reversed. The icon shows the bottom going to the top and the top going to the bottom. It's difficult to conceive of a better one. It's the best out of the two sets of standard android icons I have. I have used the same icon on my [Currency](https://github.com/billthefarmer/currency) app for reversing the graph. There is also a slide button on the fascia of the app.

Also, if you are holding the device correctly you can't see the buttons and you can't feel them as you can on a real instrument so I fail to see how anyone can play it, especially on a phone. I can't.
