### ISSUE TITLE
Add option for 5 button rows

### ISSUE THREAD

**Issue by Glitchy-Tozier** [billthefarmer/accordion#15]
Chromatic accordions (C-/B-System) sometimes have 4, 5 (most common) or even 6 button rows on the right hand, where the top rows are duplicates of the 3 "normal" ones.

This would be a great addition to your app.

As such a feature would take up a lot of space, I suggest that we disable the left hand's buttons while 5 rows are present.

Image of a 5-button-accordion: https://media.rainpos.com/7832/img_0881.jpg

**Comment by billthefarmer** [comment]
In B and C system accordions with more than three rows the extra rows are linked mechanically to the first three rows, so the instrument is really three row with extended button levers. In the app extra rows would have to be extra rows of buttons which would require a redesign of the app.

**Comment by Glitchy-Tozier** [comment]
Got it, closing the issue, then!
