### ISSUE TITLE
Play with USB keyboard

### ISSUE THREAD

**Issue by arretxe** [billthefarmer/accordion#16]
It would be amazing to be able to play the accordion with a USB keyboard, the spacebar being the trigger for the bellow. It could have a default key to note asignation map, but it would be better to make it configurable because there are different types of keyboard layouts, QWERTY, AZERTY...

**Comment by billthefarmer** [comment]
I already have a desktop app that does this &ndash; https://github.com/billthefarmer/c-accordion.

As with that app, I would use the default QWERTY keyboard layout, as the android API identifies keyboard keys by function rather than keyboard position.

**Comment by arretxe** [comment]
Amazing! But it would be great to have it on the phone, just plug any USB keyboard and play!
Regarding the API, then you don't assign a letter to a note, but a position to a note?
Anyhow, I think making that configurable would enable setting different kinds of accordions (basque, irish, mexican...)

**Comment by billthefarmer** [comment]
I had a preliminary experiment. As I don't have a USB keyboard I tested with [scrcpy](https://github.com/Genymobile/scrcpy) and found that the tab and arrow keys navigate round the display, the space key presses buttons and the escape key exits the app. I don't know if this is android or scrcpy being clever.

The QWERTY layout should work OK with UK and US keyboards, but not necessarily with other layouts.

**Comment by billthefarmer** [comment]
OK, this is not that satisfactory using scrcpy, but it might work better with a directly connected keyboard. The keys are...
```
 WERTYUIOP[
ASDFGHJKL;'
 ZXCVBNM,./
```
The basses are on the function keys and the number keys, the spacebar and the left and right shift keys are the bellows. On my keyboard the function keys do nothing, the spacebar presses buttons as above, the letter keys word as expected and the number and punctuation keys behave as if pressed and released. See if your setup works better.

[Accordion-debug.zip](https://github.com/billthefarmer/accordion/files/9336003/Accordion-debug.zip)

**Comment by arretxe** [comment]
Amazing! I have tried it briefly and it works great, except the space bar doesn't act the bellow, both shifts do
