### ISSUE TITLE
[Feature request] Add Dark Mode

### ISSUE THREAD

**Issue by DrDustwolf** [billthefarmer/accordion#17]
Please add a Dark Mode to the Application. One with true Black for OLED screns. An option to change the Text-, Back- and Foreground Colours would also be appreciated! It would also be nice if one can set an individual Picture as Background.

Thanks

**Comment by billthefarmer** [comment]
It's possible to add a dark mode, but bear in mind this will only work in the settings. Adding facilities for changing colours or loading external images is outside the scope of the app.
