### ISSUE TITLE
[Feature request] solfeggio frequencies

### ISSUE THREAD

**Issue by DrDustwolf** [billthefarmer/accordion#18]
Please add the posibility to tune the concert pitch to the solfeggio frequencies and maybe also to other frequencies as the user set's them or as known to be good in general. Thanks! :)

**Comment by billthefarmer** [comment]
The app uses the android built in midi synthesizer for the output notes. I don't know if midi or the android implementation supports what you are asking for, but it is outside the scope of the app.
