### ISSUE TITLE
Feature request: motion sensing billows

### ISSUE THREAD

**Issue by hackerb9** [billthefarmer/accordion#3]
The app does not currently seem to change the sound when I move the tablet as I play. It'd be very fun if it could make the in-and-out noises based on the gyroscopic motion sensor. As an added benefit, anyone could strap their tablet to their hand and play the Air Accordion. (Which is so much cooler than an air guitar.)

**Comment by billthefarmer** [comment]
I have released a new version with a layout for smaller devices. I am testing using the gyroscope to change the bellows.direction. However the Moto G phone I am using to test the smaller layout doesn't have a gyroscope or anything else of much use for detecting rotation.

**Comment by billthefarmer** [comment]
I have tested this and couldn't get it to work satisfactorily.

**Comment by hackerb9** [comment]
Is the motion sensing code still in the app so others can try to improve it? What happened that was unsatisfactory?

**Comment by billthefarmer** [comment]
The gyroscope code is here: https://github.com/billthefarmer/accordion/tree/gyroscope. I found it unreliable, not a lot of use for playing an instrument, and not all devices have a gyro. My Moto G doesn't have anything that's usable. There's an app on F-Droid - Sensor Readout that shows all the sensors on a device.
