### ISSUE TITLE
add change log to fdroid

### ISSUE THREAD

**Issue by treakiandroid** [billthefarmer/accordion#6]
hi,

could you please add a link version changelog to the fdroid repo. thanks in advance!

**Comment by treakiandroid** [comment]
oh, lookes like ive requested that again, sry. but it isn't there yet. can you give me a link to the changelog page here and to githubs readme for the meantime? thanks

**Comment by billthefarmer** [comment]
I'm a bit puzzled as to why you need a link here. Both the changelog and the README are one click away from the source code link. Your app, Vector Pinball doesn't have a changelog link on F-Droid either. And [locutis-of-borg-1999](https://github.com/locutis-of-borg-1999) has raised an issue about it.

https://github.com/billthefarmer/accordion/releases
https://github.com/billthefarmer/accordion/blob/master/README.md
